const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { _electron } = require('playwright-core');

async function main() {
  const root = path.resolve(__dirname, '..');
  const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'study-desk-smoke-'));
  const screenshots = path.join(root, '.tmp');
  fs.mkdirSync(screenshots, { recursive: true });
  const answerFile = path.join(temp, 'answer.pdf');
  fs.writeFileSync(answerFile, '%PDF-1.4\n%%EOF\n');
  const app = await _electron.launch({ executablePath: require('electron'), args: [root], cwd: root, env: { ...process.env, STUDY_DATA_DIR: path.join(temp, 'appdata') } });
  try {
    await app.firstWindow();
    if (app.windows().length < 2) await app.waitForEvent('window', { timeout: 10000 });
    const windows = app.windows();
    const titled = await Promise.all(windows.map(async (window) => ({ window, title: await window.title() })));
    const page = titled.find((item) => item.title === '知序学习')?.window;
    if (!page) throw new Error(`主窗口未打开：${titled.map((item) => item.title).join(', ')}`);
    await page.getByText('我的学习空间').waitFor();
    await page.screenshot({ path: path.join(screenshots, 'home.png') });
    await page.getByRole('button', { name: '新建课程' }).first().click();
    await page.getByPlaceholder('例如：一元二次方程').fill('函数入门');
    await page.getByPlaceholder('在这里写入这节课需要掌握的知识点').fill('函数描述输入与输出之间的关系。');
    await page.getByPlaceholder('输入题目内容，支持文字与图片').fill('求 f(2)，其中 f(x)=x+3。');
    await page.getByRole('button', { name: '保存课程' }).click();
    await page.getByRole('button', { name: '开始学习' }).click();
    await page.getByText('函数描述输入与输出之间的关系。').waitFor();
    await page.screenshot({ path: path.join(screenshots, 'lesson.png') });
    await page.getByRole('button', { name: '完成，开始做题' }).click();
    const overlay = app.windows().find((window) => window !== page);
    await overlay.getByText('求 f(2)，其中 f(x)=x+3。').waitFor();
    await overlay.screenshot({ path: path.join(screenshots, 'overlay.png') });
    assert(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find((win) => win.getTitle() === '题目悬浮窗').isAlwaysOnTop()));
    await app.evaluate(({ ipcMain }) => {
      ipcMain.removeHandler('codex:list');
      ipcMain.handle('codex:list', () => [{ id: '11111111-1111-1111-1111-111111111111', title: '学习测试' }]);
      ipcMain.removeHandler('codex:ask');
      ipcMain.handle('codex:ask', () => ({ needsDesktop: true }));
      ipcMain.removeHandler('codex:desktop');
      ipcMain.handle('codex:desktop', () => '这是返回的学习解答。');
    });
    await overlay.getByRole('button', { name: 'AI 聊天' }).click();
    await overlay.locator('#chat-input').waitFor();
    assert.equal(await overlay.locator('.question-text').count(), 0);
    await overlay.getByPlaceholder('输入你的问题…').fill('2+2 等于几？');
    await overlay.getByRole('button', { name: '发送', exact: true }).click();
    await overlay.getByRole('button', { name: '复制问题并打开 Codex' }).click();
    await overlay.getByText('这是返回的学习解答。').waitFor();
    await overlay.screenshot({ path: path.join(screenshots, 'chat.png') });
    await overlay.getByRole('button', { name: '返回题目' }).click();
    await overlay.getByText('求 f(2)，其中 f(x)=x+3。').waitFor();
    await overlay.getByRole('button', { name: '完成', exact: false }).click();
    await page.getByRole('button', { name: '选择 PDF 或图片' }).waitFor();
    await app.evaluate(({ dialog }, files) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [files.shift()] }); }, [answerFile, temp]);
    await page.getByRole('button', { name: '选择 PDF 或图片' }).click();
    await page.getByRole('button', { name: '生成批改包' }).click();
    await page.getByText('批改包已生成').waitFor();
    const folders = fs.readdirSync(temp).filter((name) => name.includes('-提交-'));
    assert.equal(folders.length, 1);
    const files = fs.readdirSync(path.join(temp, folders[0]));
    assert(files.includes('批改材料.html'));
    assert(files.includes('作答文件.pdf'));
    await page.getByRole('button', { name: '新建课程' }).first().click();
    await page.getByPlaceholder('例如：一元二次方程').fill('OneNote 演示');
    await page.getByPlaceholder('在这里写入这节课需要掌握的知识点').fill('第二课知识点');
    await page.getByPlaceholder('输入题目内容，支持文字与图片').fill('第二课题目');
    await page.getByRole('button', { name: 'OneNote', exact: true }).click();
    await page.getByPlaceholder('onenote:https://...').fill('onenote:https://example.com/page');
    await page.screenshot({ path: path.join(screenshots, 'onenote-settings.png') });
    await page.getByRole('button', { name: '保存课程' }).click();
    await app.evaluate(({ shell }) => { shell.openExternal = async (url) => { globalThis.__studyOpenedUrl = url; }; });
    await page.locator('.course-card').filter({ hasText: 'OneNote 演示' }).getByRole('button', { name: '开始学习' }).click();
    await page.getByRole('button', { name: '完成，开始做题' }).click();
    await overlay.getByText('第二课题目').waitFor();
    const openedUrl = await app.evaluate(() => globalThis.__studyOpenedUrl);
    assert.equal(openedUrl, 'onenote:https://example.com/page');
    const captureReady = app.waitForEvent('window');
    await overlay.getByRole('button', { name: '截图' }).click();
    const capture = await captureReady;
    await capture.getByText('框选需要提交的作答区域').waitFor();
    await capture.mouse.move(120, 160);
    await capture.mouse.down();
    await capture.mouse.move(460, 400);
    await capture.mouse.up();
    await capture.getByRole('button', { name: '保存第 1 题并继续' }).click();
    await page.getByText('第 01 题 · 已截图').waitFor();
    assert(await page.locator('.submission-preview').evaluate((img) => img.src.startsWith('data:image/png;base64,')));
    await page.getByRole('button', { name: '返回做题' }).click();
    await overlay.getByRole('button', { name: '完成', exact: false }).click();
    await page.getByText('第 01 题 · 已截图').waitFor();
    await page.screenshot({ path: path.join(screenshots, 'screenshot-submit.png') });
    await app.evaluate(({ dialog }, temp) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [temp] }); }, temp);
    await page.getByRole('button', { name: '生成批改包' }).click();
    await page.getByText('批改包已生成').waitFor();
    const imageFolder = fs.readdirSync(temp).find((name) => name.startsWith('OneNote 演示-提交-'));
    const png = fs.readFileSync(path.join(temp, imageFolder, '第01题-作答.png'));
    assert.equal(png.subarray(1, 4).toString(), 'PNG');
    assert(png.readUInt32BE(16) >= 340 && png.readUInt32BE(20) >= 240);
    await page.getByRole('button', { name: '新建课程' }).first().click();
    await page.getByPlaceholder('例如：一元二次方程').fill('自选程序演示');
    await page.getByPlaceholder('在这里写入这节课需要掌握的知识点').fill('第三课知识点');
    await page.getByPlaceholder('输入题目内容，支持文字与图片').fill('第三课题目');
    await page.getByRole('button', { name: '指定程序' }).click();
    await app.evaluate(({ dialog }) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: ['C:\\Windows\\notepad.exe'] }); });
    await page.getByRole('button', { name: '选择 .exe 程序' }).click();
    await page.getByRole('button', { name: '保存课程' }).click();
    const savedCourses = await page.evaluate(() => window.study.listCourses());
    assert.equal(savedCourses.find((item) => item.title === '自选程序演示').workTarget.appPath, 'C:\\Windows\\notepad.exe');
    console.log(`Smoke test passed. Screenshots: ${screenshots}`);
  } finally {
    await app.close();
  }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
