const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('study', {
  getAISettings: () => ipcRenderer.invoke('ai:settings:get'),
  switchAIMode: (mode) => ipcRenderer.invoke('ai:mode', mode),
  saveAISettings: (input) => ipcRenderer.invoke('ai:settings:save', input),
  chatHistory: (input) => ipcRenderer.invoke('chat:history', input),
  compactContext: (input) => ipcRenderer.invoke('chat:compact', input),
  clearContext: (input) => ipcRenderer.invoke('chat:clearContext', input),
  openSettings: () => ipcRenderer.invoke('settings:open'),
  onAISettings: (callback) => { const listener=(_event,value)=>callback(value);ipcRenderer.on('ai:settings',listener);return ()=>ipcRenderer.removeListener('ai:settings',listener); },
  onOpenSettings: (callback) => ipcRenderer.on('settings:open',(_event,value)=>callback(value)),
  listCourses: () => ipcRenderer.invoke('courses:list'),
  importCourseFile: () => ipcRenderer.invoke('courses:importFile'),
  saveCourse: (course) => ipcRenderer.invoke('courses:save', course),
  deleteCourse: (id) => ipcRenderer.invoke('courses:delete', id),
  chooseImage: () => ipcRenderer.invoke('dialog:image'),
  chooseWorkFile: () => ipcRenderer.invoke('dialog:workFile'),
  chooseWorkApp: () => ipcRenderer.invoke('dialog:workApp'),
  chooseAnswerFile: () => ipcRenderer.invoke('dialog:answerFile'),
  startSession: (id) => ipcRenderer.invoke('session:start', id),
  resumeSession: () => ipcRenderer.invoke('session:resume'),
  finishSession: () => ipcRenderer.invoke('session:finish'),
  navigateQuestion: (index) => ipcRenderer.invoke('session:navigate', index),
  pauseSession: () => ipcRenderer.invoke('session:pause'),
  startCapture: (purpose = 'answer') => ipcRenderer.invoke('capture:start', purpose),
  cancelCapture: () => ipcRenderer.invoke('capture:cancel'),
  commitCapture: (rect) => ipcRenderer.invoke('capture:commit', rect),
  listCodexThreads: () => ipcRenderer.invoke('codex:list'),
  codexPreferences: () => ipcRenderer.invoke('codex:preferences'),
  codexConnection: () => ipcRenderer.invoke('codex:connection'),
  selectCodexThread: (id) => ipcRenderer.invoke('codex:select', id),
  continueInCodex: (message) => ipcRenderer.invoke('codex:desktop', message),
  cancelCodex: () => ipcRenderer.invoke('codex:cancel'),
  askCodex: (message) => ipcRenderer.invoke('codex:ask', message),
  askLesson: (input) => ipcRenderer.invoke('lesson:ask', input),
  onLessonAnswer: (callback) => { const listener = (_event, text) => callback(text); ipcRenderer.on('lesson:answer', listener); return () => ipcRenderer.removeListener('lesson:answer', listener); },
  exportSubmission: (file) => ipcRenderer.invoke('submission:export', file),
  gradeSubmission: (input) => ipcRenderer.invoke('submission:grade', input),
  onGradeProgress: (callback) => ipcRenderer.on('submission:gradeProgress', (_event, data) => callback(data)),
  openFolder: (folder) => ipcRenderer.invoke('submission:openFolder', folder),
  onCourse: (callback) => ipcRenderer.on('session:course', (_event, course) => callback(course)),
  onProgress: (callback) => ipcRenderer.on('session:progress', (_event, progress) => callback(progress)),
  onSubmit: (callback) => ipcRenderer.on('session:submit', (_event, id, options) => callback(id, options)),
  onPaused: (callback) => ipcRenderer.on('session-paused', () => callback()),
  onCaptureImage: (callback) => ipcRenderer.on('capture:image', (_event, image) => callback(image)),
  onCaptureQuestion: (callback) => ipcRenderer.on('capture:question', (_event, number) => callback(number)),
  onCapturePurpose: (callback) => ipcRenderer.on('capture:purpose', (_event, purpose) => callback(purpose)),
  onChatCapture: (callback) => ipcRenderer.on('chat:capture', (_event, image) => callback(image)),
  onCodexDelta: (callback) => ipcRenderer.on('codex:delta', (_event, delta) => callback(delta)),
  onCodexAnswer: (callback) => ipcRenderer.on('codex:answer', (_event, text) => callback(text)),
});
