// SPDX-FileCopyrightText: 2026 ltebsxy
// SPDX-License-Identifier: GPL-3.0-only
const { contextBridge, ipcRenderer } = require('electron');
let currentTheme=ipcRenderer.sendSync('theme:initial');
ipcRenderer.on('theme:changed',(_event,state)=>{currentTheme=state;});
contextBridge.exposeInMainWorld('study', {
  themeSnapshot: () => currentTheme,
  getTheme: () => ipcRenderer.invoke('theme:get'),
  saveTheme: mode => ipcRenderer.invoke('theme:save',mode),
  onTheme: callback => {const listener=(_event,state)=>callback(state);ipcRenderer.on('theme:changed',listener);return ()=>ipcRenderer.removeListener('theme:changed',listener);},
  getWritingSettings: () => ipcRenderer.invoke('writing:settings:get'),
  saveWritingSettings: (input) => ipcRenderer.invoke('writing:settings:save', input),
  getAISettings: () => ipcRenderer.invoke('ai:settings:get'),
  getChatGPTState: () => ipcRenderer.invoke('chatgpt:state'),
  loginChatGPT: input => ipcRenderer.invoke('chatgpt:login',input),
  cancelChatGPTLogin: () => ipcRenderer.invoke('chatgpt:cancel'),
  chatGPTModels: id => ipcRenderer.invoke('chatgpt:models',id),
  logoutChatGPT: id => ipcRenderer.invoke('chatgpt:logout',id),
  acknowledgeChatGPTWelcome: id => ipcRenderer.invoke('chatgpt:welcome',id),
  manageChatGPTUsage: () => ipcRenderer.invoke('chatgpt:usage'),
  switchAIMode: (mode) => ipcRenderer.invoke('ai:mode', mode),
  saveAISettings: (input) => ipcRenderer.invoke('ai:settings:save', input),
  chatHistory: (input) => ipcRenderer.invoke('chat:history', input),
  compactContext: (input) => ipcRenderer.invoke('chat:compact', input),
  clearContext: (input) => ipcRenderer.invoke('chat:clearContext', input),
  openSettings: () => ipcRenderer.invoke('settings:open'),
  onAISettings: (callback) => { const listener=(_event,value)=>callback(value);ipcRenderer.on('ai:settings',listener);return ()=>ipcRenderer.removeListener('ai:settings',listener); },
  onOpenSettings: (callback) => ipcRenderer.on('settings:open',(_event,value)=>callback(value)),
  library: () => ipcRenderer.invoke('library:get'),
  saveFolder: input => ipcRenderer.invoke('library:folder',input),
  removeFolder: input => ipcRenderer.invoke('library:removeFolder',input),
  assignFolder: input => ipcRenderer.invoke('library:assign',input),
  selectFolder: input => ipcRenderer.invoke('library:select',input),
  importPDF: input => ipcRenderer.invoke('library:importPDF',input),
  importReadingFolder: input => ipcRenderer.invoke('library:importReadingFolder',input),
  syncCourses: (revision) => ipcRenderer.invoke('courses:sync', revision),
  listCourses: () => ipcRenderer.invoke('courses:list'),
  importCourseFile: () => ipcRenderer.invoke('courses:importFile'),
  saveCourse: (course) => ipcRenderer.invoke('courses:save', course),
  chooseProgrammingFolder: () => ipcRenderer.invoke('programming:chooseFolder'),
  startProgramming: id => ipcRenderer.invoke('programming:start',id),
  openProgrammingExternal: id => ipcRenderer.invoke('programming:openExternal',id),
  programmingFiles: id => ipcRenderer.invoke('programming:files',id),
  programmingRead: input => ipcRenderer.invoke('programming:read',input),
  programmingWrite: input => ipcRenderer.invoke('programming:write',input),
  programmingChatToggle: expanded => ipcRenderer.invoke('programming:chatToggle',expanded,!matchMedia('(prefers-reduced-motion: reduce)').matches),
  programmingChatMove: delta => ipcRenderer.invoke('programming:chatMove',delta),
  onProgrammingChatMode: callback => ipcRenderer.on('programming:chatMode',(_event,expanded)=>callback(expanded)),
  addProgrammingSnippet: input => ipcRenderer.invoke('programming:addSnippet',input),
  onProgrammingSnippet: callback => ipcRenderer.on('programming:snippet',(_event,snippet)=>callback(snippet)),
  onProgrammingCapture: callback => ipcRenderer.on('programming:capture',(_event,capture)=>callback(capture)),
  programmingActive: () => ipcRenderer.invoke('programming:active'),
  programmingLeave: id => ipcRenderer.invoke('programming:leave',id),
  programmingAsk: input => ipcRenderer.invoke('programming:ask',input),
  programmingPropose: input => ipcRenderer.invoke('programming:propose',input),
  programmingApply: token => ipcRenderer.invoke('programming:apply',token),
  programmingSubmissionPreview: id => ipcRenderer.invoke('programming:submissionPreview',id),
  programmingShowSubmission: id => ipcRenderer.invoke('programming:showSubmission',id),
  onProgrammingSubmission: callback => ipcRenderer.on('programming:submissionReady',(_event,details)=>callback(details)),
  programmingSubmit: input => ipcRenderer.invoke('programming:submit',input),
  programmingGrade: submissionId => ipcRenderer.invoke('programming:grade',submissionId),
  programmingExport: submissionId => ipcRenderer.invoke('programming:export',submissionId),
  onProgrammingGradeProgress: callback => ipcRenderer.on('programming:gradeProgress',(_event,data)=>callback(data)),
  programmingWorkspaces: () => ipcRenderer.invoke('programming:workspaces'),
  programmingClearWorkspace: id => ipcRenderer.invoke('programming:clearWorkspace',id),
  deleteCourse: (id) => ipcRenderer.invoke('courses:delete', id),
  chooseImage: () => ipcRenderer.invoke('dialog:image'),
  chooseWorkFile: () => ipcRenderer.invoke('dialog:workFile'),
  chooseWorkApp: () => ipcRenderer.invoke('dialog:workApp'),
  chooseAnswerFile: () => ipcRenderer.invoke('dialog:answerFile'),
  startSession: (id, mode = 'exercise') => ipcRenderer.invoke('session:start', id, mode),
  expandExerciseOverlay: expanded => ipcRenderer.invoke('overlay:expand',expanded,!matchMedia('(prefers-reduced-motion: reduce)').matches),
  moveExerciseOverlay: delta => ipcRenderer.invoke('overlay:move',delta),
  onExerciseOverlayExpanded: callback => ipcRenderer.on('overlay:expanded',(_event,expanded)=>callback(expanded)),
  saveResponse: (input) => ipcRenderer.invoke('session:answer', input),
  writerAIState: () => ipcRenderer.invoke('writer:aiState'),
  toggleWriterAI: input => ipcRenderer.invoke('writer:toggleAI',input),
  onWriterAIVisibility: callback => ipcRenderer.on('writer:aiVisibility',(_event,visible)=>callback(visible)),
  onOpenChat: callback => ipcRenderer.on('chat:open',()=>callback()),
  openWriter: () => ipcRenderer.invoke('writer:open'),
  readerSource: input => ipcRenderer.invoke('reader:source', input),
  lookupEnglishWord: input => ipcRenderer.invoke('reader:lookup', input),
  writerLoad: () => ipcRenderer.invoke('writer:load'),
  writerSave: (data) => ipcRenderer.invoke('writer:save', data),
  writerSubmit: (input) => ipcRenderer.invoke('writer:submit', input),
  resumeSession: () => ipcRenderer.invoke('session:resume'),
  finishSession: () => ipcRenderer.invoke('session:finish'),
  navigateQuestion: (index) => ipcRenderer.invoke('session:navigate', index),
  pauseSession: () => ipcRenderer.invoke('session:pause'),
  startCapture: (purpose = 'answer') => ipcRenderer.invoke('capture:start', purpose),
  cancelCapture: () => ipcRenderer.invoke('capture:cancel'),
  commitCapture: (rect) => ipcRenderer.invoke('capture:commit', rect),
  listCodexThreads: () => ipcRenderer.invoke('codex:list'),
  codexPreferences: () => ipcRenderer.invoke('codex:preferences'),
  codexConnection: () => ipcRenderer.invoke('codex:connection'),
  selectCodexThread: (id) => ipcRenderer.invoke('codex:select', id),
  continueInCodex: (message) => ipcRenderer.invoke('codex:desktop', message),
  cancelCodex: () => ipcRenderer.invoke('codex:cancel'),
  askCodex: (message) => ipcRenderer.invoke('codex:ask', message),
  askLesson: (input) => ipcRenderer.invoke('lesson:ask', input),
  onLessonAnswer: (callback) => { const listener = (_event, text) => callback(text); ipcRenderer.on('lesson:answer', listener); return () => ipcRenderer.removeListener('lesson:answer', listener); },
  exportSubmission: (file) => ipcRenderer.invoke('submission:export', file),
  gradeSubmission: (input) => ipcRenderer.invoke('submission:grade', input),
  onGradeProgress: (callback) => ipcRenderer.on('submission:gradeProgress', (_event, data) => callback(data)),
  openFolder: (folder) => ipcRenderer.invoke('submission:openFolder', folder),
  onCourse: (callback) => ipcRenderer.on('session:course', (_event, course) => callback(course)),
  onProgress: (callback) => ipcRenderer.on('session:progress', (_event, progress) => callback(progress)),
  onSubmit: (callback) => ipcRenderer.on('session:submit', (_event, id, options) => callback(id, options)),
  onPaused: (callback) => ipcRenderer.on('session-paused', (_event, state) => callback(state)),
  onCaptureImage: (callback) => ipcRenderer.on('capture:image', (_event, image) => callback(image)),
  onCaptureQuestion: (callback) => ipcRenderer.on('capture:question', (_event, number) => callback(number)),
  onCapturePurpose: (callback) => ipcRenderer.on('capture:purpose', (_event, purpose) => callback(purpose)),
  onChatCapture: (callback) => ipcRenderer.on('chat:capture', (_event, image) => callback(image)),
  onCodexDelta: (callback) => ipcRenderer.on('codex:delta', (_event, delta) => callback(delta)),
  onCodexAnswer: (callback) => ipcRenderer.on('codex:answer', (_event, text) => callback(text)),
});
